### ISSUE TITLE
Create "2 Column" Layout Component

### ISSUE THREAD

**Issue by mistryrn** [CancerCollaboratory/website#9]
- [x] Create a reusable `LateralColumn` (layout) component
- [x] Add support to `LateralColumn` for `Our Services` page
- [x] Create a responsive design that supports various elements
- [x] Add support for single (mobile) and double (desktop) columns
- [x] Create a `Column` (layout) component for left and right columns
- [x] Build flexible `LeftColumn` and `RightColumn` components
