### ISSUE TITLE
Build The Home Page

### ISSUE THREAD

**Issue by dhyeypatell** [CancerCollaboratory/website#95]
- [x] Use components to complete Home
- [x] Add data for components in `data/pages/home/home.json`
- [x] Use data from `data/pages/home/home.json`
- Page: https://cancercollaboratory.org
